"""
Django settings for djangoTest project.

Generated by 'django-admin startproject' using Django 1.8.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(__file__))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4qhiy&s1=#8034xg13jt+&y4=w!d15209#y9nr#*ua^pf3(c=0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False


# see https://docs.djangoproject.com/en/1.8/ref/settings/#std%3asetting-ALLOWED_HOSTS
# Bad Request (400) will appear without it
ALLOWED_HOSTS = [
    '*.test.domain.com.',
]


# Application definition

DEFAULT_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
)

THIRD_PARTY_APPS = (
    'django_tables2',
)

LOCAL_APPS = (
    'sqldata',
    'ifrate',
    'getmacs',
    'netmon.acl',
)

INSTALLED_APPS = DEFAULT_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'netmon.acl.middleware.IPAccessMiddleware',
)

ROOT_URLCONF = 'netmon.urls'

# Put strings here, like "/home/html/django_templates" or "C:/www/django/templates".
# Always use forward slashes, even on Windows.
# Don't forget to use absolute paths, not relative paths.
TEMPLATE_DIRS = (os.path.join(os.path.dirname(__file__), 'templates'), )

WSGI_APPLICATION = 'netmon.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',     # Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
        'NAME': 'basename',                #'core_collect_test', # core_collect_m
        'USER': 'user',                    # Not used with sqlite3.
        'PASSWORD': '12345',               # Not used with sqlite3.
        'HOST': 'stat-db',                 # Set to empty string for localhost. Not used with sqlite3.
        'PORT': '5433',                    # Set to empty string for default. Not used with sqlite3.
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.6/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.6/howto/static-files/

# used for collectstatic
# STATIC_ROOT = os.path.join(BASE_DIR, 'static') # best way, but you have to make /static dir in root
# STATIC_ROOT = os.path.join(os.path.dirname(__file__), 'static') # /netmon/netmon/static dir. its ok for small site.

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
    os.path.join(os.path.dirname(__file__), 'static'),
)

#
# Globals
########################################################################################################################

# my table names for Django ORM integration
SQL_DEVTABLE = 'devices'
SQL_INTERFACES = 'interfaces'
SQL_DATA = 'snmpdata'

# using in .strftime()
MYDATETIME_FORMAT = '%d.%m.%Y %H:%M'
